### PR TITLE
Support for Github Actions and static build

### LINKED ISSUE #25: Add support for Github Actions

### PR DESCRIPTION
**Pull request by lehins**
Added support for Github Actions and added flags for ghc that  do a static build by default

Fixes #25

### CODE REVIEW

**Comment by rubik** [comment]
Thanks @lehins! Sorry for the extreme delay! This project needs a maintainer as I am unable to allocate time to it right now (and that has been the situation for a long time), do you want to step in? I can give you permission to release new versions too.

**Comment by lehins** [comment]
@rubik I do have many things on my plate as well, however I am using this tool for a few of my projects, so if you do give me permission to the repo I could certainly help out a bit, especially considering I am already keeping a fork of this repo going.

To put in other words, I can't promise active development, but I can try to help you keep this project alive and functional.

**Comment by rubik** [comment]
@lehins That would be great, it's already much more than I can do at the moment. I invited you as a collaborator on this repository. If you tell me your username on Hackage, I can make you a maintainer there too. Thanks again!

**Comment by lehins** [comment]
Cool thanks. My username on hackage is also [lehins](https://hackage.haskell.org/user/lehins).
I'll try to make a release over the next weekend.

**Comment by rubik** [comment]
@lehins Great, I just added you to Hackage!

**Comment by lehins** [comment]
@rubik Awseome. Thank you.

We do have #27 however as a blocker before we can upload new versions to hackage.

**Pull request merged**
